name: NPM-publish

on:
    workflow_dispatch:

    push:
        branches:
            - 'main'
        paths:
            - 'index.js'
            - package.json
            - package-lock.json
            - README.rnd

jobs:
    validate:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install app
              run: npm ci

            - name: Lint app
              run: npm run lint:check

            - name: Prettier app
              run: npm run format:check

            - name: Test app
              run: npm run test

    publish:
        runs-on: ubuntu-latest
        needs: validate
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install
              run: npm ci

            - name: Copy README
              run: cp ../README.md README.md

            - name: Copy LICENSE
              run: cp ../LICENSE LICENSE

            - uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
                  package: package.json
                  strategy: all
